FROM node:14-alpine as builder

RUN apk add --no-cache gcc autoconf automake build-base libpng-dev nasm
RUN npm install -g serve 
WORKDIR /app

RUN chown node:node /app

COPY package.json .
COPY yarn.lock .

COPY . .

ENV NODE_ENV=development

ENTRYPOINT [ "./entrypoint.sh" ]

# FROM ghcr.io/socialgouv/docker/nginx4spa:6.70.0

# COPY --from=builder /app/build /usr/share/nginx/html
